const args = require("minimist")(process.argv.slice(2));
const fs = require("fs-extra");
const path = require("path");
const JSZip = require('jszip');
const cheerio = require('cheerio');
const config = {
    epub: String(args._.length ? args._[0] : "1.epub"),
    html: "",
    src: "",
    dark: args.d||args.dark?1:0,
    log: args.l?1:0
}
config.html = config.epub.replace(/\.[^\.]+?$|$/, ".html"),
config.src = config.epub.replace(/\.[^\.]+?$|$/, "")
//console.log(config);


fs.readFile(config.epub, (err, data) => {
    JSZip.loadAsync(data).then(async (zip) => {
        const xml = await zip.file('META-INF/container.xml').async('string');
        let $ = cheerio.load(xml, {
            xmlMode: true
        });
        const opf = await zip.file($('rootfile').attr('full-path')).async("string");
        let suf=$('rootfile').attr('full-path').match(/^.+\//);
        if(!suf)suf="";

        let chapters = {},
            src = {},
            css = [],
            meta = {};
        $ = cheerio.load(opf, {
            xmlMode: true
        });

        //提取元元素
        $("metadata *").each(function () {
            attr = this.name.match(/(?<=^dc:).+/);
            if (attr)
                meta[attr[0]] = $(this).text();
        })
        //console.log(meta);

        //提取章节、css、资源
        $("item").each(function () {
            let href = this.attribs.href;
            if (href.match(/\.x?html$/i))
                chapters[this.attribs.id] =href;
            else if (href.match(/\.css$/i))
                css.push(href);
            else if (href.match(/\.(jpe?g|png|gif|svg|ttf|otf)$/i))
                src[this.attribs.id] = decodeURIComponent(href);
        })

        //初始化输出html
        let html = cheerio.load(`<!DOCTYPE html>
    <html lang="zh-cn">
        <!--Generated by SXZ-epub2html / sxz-oi.github.io-->
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <link rel="shortcut icon" href="ico.png" />
            <style>${fs.readFileSync(config.dark?"dark.css":"default.css")}</style>
        </head>
        <body>
        </body>
    </html>`),
            ref = $("itemref");

        //元信息
        html("body").append(`<header id="title-block-header">
        <h1 class="head-title">${meta.title}</h1>
        <p class="head-creator">${meta.creator}</p>
        <p class="head-date">${meta.date}</p>
        </header>`)
        for (var i in meta) {
            let temp = html("<meta>"); //不知道为什么直接append字符串还有bug的。。。只好创建元素了
            temp.attr("name", i), temp.attr("content", meta[i])
            html("head").append(temp);
            if(config.log)console.log("\x1B[0m\x1B[1m添加元: \x1B[34m"+i,meta[i]);
        }
        html("head").append(`<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes"><title>${meta.title}</title>`)

        for (var i in src){
            let file=zip.file(suf+src[i]);
            if(!file){
                console.warn("\x1B[31m%s\x1B[0m",src[i]+" does not exist");
                continue;
            }
            file=await file.async('nodebuffer');
            fs.outputFileSync(config.src + "/" + src[i],file)
            if(config.log)console.log("\x1B[0m\x1B[1m提取: \x1B[34m"+src[i]);
        }

        //加入css
        for (var i in css)
            html("head").append(`<style id="${css[i]}">` + (await zip.file(suf+css[i]).async("string")).replace(/(?<=url\()(\.\.\/|)(.+?)(?=\))/g,`${config.src}/$2`) + "</style>")
        
        //加入各章节
        for (var i = 0; i < ref.length; i++) {
            let x = ref[i].attribs.idref,
                px=chapters[x].replace(new RegExp(`^${suf}/`),"").split("/").reverse();
            let raw=await zip.file(suf+chapters[x]).async("string");
            raw=raw.replace(/<\?.+?>|\r/,"")
            let chapter = cheerio.load(raw,{xmlMode: false});
            
            chapter("img").each(function(){
                this.attribs.src=config.src+"/"+this.attribs.src.replace(/\.\.\//,(v,u)=>px[u+2]?px[u+2]+"/":"")
            });
            chapter("image").each(function(){
                this.attribs.href=config.src+"/"+this.attribs.href.replace(/\.\.\//,(v,u)=>px[u+2]?px[u+2]+"/":"")
            });
            chapter("a").each(function(){
                if(this.attribs.href.match(/^#|http/))
                    return;
                this.attribs.href="#"+this.attribs.href.replace(/#.+|(.+\/)/, "");
            });
            //修改各种URL

            chapter("body").children().wrapAll("<section></section>");
            chapter("section").attr("id", chapters[x].replace(/.+\//,""));
            html("body").append(chapter("body").html());
            if(config.log)console.log("\x1B[0m\x1B[1m添加章节: \x1B[34m"+x);
        }

        //输出
        console.log('\x1B[1m\x1B[32m♻ Convert Over!\x1B[0m')
        fs.writeFileSync(config.html, html.html());
    });
});